export const weatherConditions = new Map([
  [0, 'Clear sky'],
  [1, 'Mainly clear'],
  [2, 'Partly cloudy'],
  [3, 'Overcast'],
  [45, 'Fog'],
  [48, 'Fog'],
  [51, 'Light drizzle'],
  [53, 'Moderate drizzle'],
  [55, 'Dense intensity drizzle'],
  [56, 'Light freezing drizzle'],
  [57, 'Dense intensity freezing drizzle'],
  [61, 'Light rain'],
  [63, 'Moderate rain'],
  [65, 'Heavy rain'],
  [66, 'Light freezing rain'],
  [67, 'Heavy freezing rain'],
  [71, 'Light snowfall'],
  [73, 'Moderate snowfall'],
  [75, 'Heavy snowfall'],
  [77, 'Snow grains'],
  [80, 'Slight rain shower'],
  [81, 'Moderate rain shower'],
  [82, 'Heavy rain shower'],
  [85, 'Slight snow shower'],
  [86, 'Heavy snow shower'],
  [95, 'Thunderstorm'],
  [96, 'Thunderstorm with slight hail'],
  [99, 'Thunderstorm with heavy hail'],
]);

// export const weatherConditions = {
//   0: 'Clear sky',
//   1: 'Mainly clear',
//   2: 'Partly cloudy',
//   3: 'Overcast',
//   45: 'Fog',
//   48: 'Fog',
//   51: 'Light drizzle',
//   53: 'Moderate drizzle',
//   55: 'Dense intensity drizzle',
//   56: 'Light freezing drizzle',
//   57: 'Dense intensity freezing drizzle',
//   61: 'Light rain',
//   63: 'Moderate rain',
//   65: 'Heavy rain',
//   66: 'Light freezing rain',
//   67: 'Heavy freezing rain',
//   71: 'Light snowfall',
//   73: 'Moderate snowfall',
//   75: 'Heavy snowfall',
//   77: 'Snow grains',
//   80: 'Slight rain shower',
//   81: 'Moderate rain shower',
//   82: 'Heavy rain shower',
//   85: 'Slight snow shower',
//   86: 'Heavy snow shower',
//   95: 'Thunderstorm',
//   96: 'Thunderstorm with slight hail',
//   99: 'Thunderstorm with heavy hail',
// };
